name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        compiler: [ gcc, clang ]

    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            brew install make
          else
            sudo apt-get install make
          fi
      - name: Build
        run: make
      - name: Run
        run: ./bin/queens
